# Base configs
baseurl: "https://merchantscp2.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Amit M"
subtitle: "See the world through my eyes!"
author: "Amit Merchant"
header:
 title: "Photography"
 subtitle: "by Amit Merchant"
footer:
 name: "Hello, my name is Amit."
 bio: "I gravitated towards photography at an early age and have recently gotten back into it."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
#  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/merchantscp2"
#  dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/merchantscp2"
